version: '3.8'

services:
  bot:
    build: .
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - type: bind
        source: ./education_bot.db
        target: /app/education_bot.db